server:
  port: 8084
spring:
  security:
    user:
      name: user
      password: password #PasswordEncoder.encode(password)
  application:
    name: member-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/member?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
jwt:
  secretKey: mysecret
  token:
    access-expiration-time: 1800000
    refresh-expiration-time: 604800000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost